[tool.ruff]
extend-select = ["B", "Q", "PL"]
line-length = 140
ignore = ["PLR2004", "PLR0911"]

[tool.ruff.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"

[tool.ruff.format]
quote-style = "single"

[tool.black]
skip-string-normalization = true
